// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-hAc8YZhk_5IGJbmj0PCWBAf0NTBe-c',
    appId: '1:130332478556:web:7bf1035cdf1e449561ea99',
    messagingSenderId: '130332478556',
    projectId: 'taaza-khabar-101a2',
    authDomain: 'taaza-khabar-101a2.firebaseapp.com',
    storageBucket: 'taaza-khabar-101a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYkx1pNq8V5eTzR0_L_CjoqP078qHvKuI',
    appId: '1:130332478556:android:e3f0f624ae448f8e61ea99',
    messagingSenderId: '130332478556',
    projectId: 'taaza-khabar-101a2',
    storageBucket: 'taaza-khabar-101a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3W_b8S4wUoj9GzMOxLpxR17vtWkuwuz0',
    appId: '1:130332478556:ios:0b5792f33b22e31b61ea99',
    messagingSenderId: '130332478556',
    projectId: 'taaza-khabar-101a2',
    storageBucket: 'taaza-khabar-101a2.appspot.com',
    iosBundleId: 'com.bitwisedhruv.taazaKhabar',
  );
}
